services:
  backend:
    container_name: backend
    build: backend
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/reading-tracker-db?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: dev_user
      DB_PASSWORD: dev_user_password
    restart: no
    depends_on:
      database:
          condition: service_healthy
        
  database:
    container_name: database
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reading-tracker-db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_user_password
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    container_name: frontend
    build: front/vue-project
    ports:
      - "5173:80" 
