"""
Django settings for backReadingTracker project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6$yol5#w9y_q!am69twp+79aumgt73e$^-kqpxx*v&1rmobmkq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
]

"""
# Código para configurar las sesiones y las cookies que me dio chatgpt

# Configuración de sesiones
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Almacén de sesiones en la base de datos
SESSION_COOKIE_NAME = 'mi_sesion_cookie'

# Configuración de cookies
SESSION_COOKIE_AGE = 1209600  # Duración en segundos (por ejemplo, 2 semanas)
SESSION_COOKIE_SECURE = False  # Solo enviar cookies a través de conexiones seguras (HTTPS)
SESSION_COOKIE_HTTPONLY = True  # Accesible solo a través de JavaScript en el navegador
"""

# Lo agrego para permitir peticiones de otros dominios
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173"
]

# Application definition

INSTALLED_APPS = [
    'backEnd.apps.BackendConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders'
]

""" IMPORTANTE: PARECE SER QUE EL MIDDLEWARE 'corsheaders.middleware.CorsMiddleware' HAY QUE PONERLO
LO MÁS ARRIBA POSIBLE PORQUE SINO NO SURTE EFECTO SOBRE LAS PETICIONES YA QUE AÚN NO SE ENCUENTRA CARGADO
EN LA DOCUMENTACIÓN LO PONE UNA LÑÍNA ARRIBA DE 'django.middleware.common.CommonMiddleware' """

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # paquete agregado para permitir peticiones de otros dominios
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]




ROOT_URLCONF = 'backReadingTracker.urls'



TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backReadingTracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

""" Por default estaba esto:
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""

# Esto lo agrego yo para intentar conectarme a una base de datos creada con PostgreSQL
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "mydatabase",
        "USER": "postgres",
        "PASSWORD": "G86NlH13#",
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



"""   
    "http://localhost:8080",
    "http://localhost:5173/",  # Agrega la URL de tu aplicación Vue.js
    "http://localhost:5173",
    "http://127.0.0.1:8000/",
    "http://127.0.0.1:8000",
    

    #http://localhost:5173/"""