# Generated by Django 5.0.1 on 2024-01-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backEnd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='owner',
            field=models.CharField(default='no one', max_length=200),
        ),
    ]
